### ISSUE TITLE
ToDo: implement CPP14Engine

### ISSUE THREAD

**Issue by RYOSKATE** [UnicoenProject/unicoen.ts#1]
### 文法
- [ ] struct
  - [x] struct型のメンバ変数
  - [x] structのmalloc
  - [x] structのポインタ変数
  - [ ] 未初期化フィールドの乱数初期化
- [ ] typedef (UniVariableDecとして実装)
  - [x] typedef struct node* link;
  - [x] typedef struct Point point;
- [x] 構造体
  - [x] グローバル変数  
  - [x] 宣言と同時の変数宣言
struct point { int x; int y; } p1, p2; (UniClassDecとStringがtype)
- [ ] 型に応じた未初期化変数の乱数初期化(charなどは0xFF範囲)
- [x] 関数定義
  - [x] ポインタが戻り値の関数定義
  - [x] 構造体が戻り値の関数定義
  - [x] 関数の前方宣言
- [x] for
  - [x] {}がないと一気に実行されてしまう問題
  - [x] 初期化、続行チェック、各ループ終了時の処理が空だと動かない
- [ ] Switch文
(CではUniSwitchにExprしか書けない(UniSwitchUnitとかにできない)、ExprStatementなど作るか)
- [ ] enum
- [ ] static 変数
- [ ] union
- [x] 三項演算子のtrue(UMG側のMapper生成の問題)
- [x] ifの{}がないと一気に実行されてしまう問題
- [ ] 多次元配列
  - [x] 素朴な未初期化2次元配列
  - [ ] 初期化リストあり
  - [ ] 3次元以上の配列
- [x] int a[10], *p;でpもint*[10]になってしまう問題

### プリプロセッサ
- [ ]  #define
  - [x] #define N 100など値に置換するもの
  - [ ]  #define prt(f) printf("%f\n", f)など式に置換するもの
### 関数
- [ ] stdio
  - [x] getChar
  - [ ] sprintf
  - [x] scanf
  - [ ] gets
- [ ] stdlib
  - [ ] atoi
- [ ] string
  - [ ] strcpy
  - [ ] strcat
  - [ ] strcmp
  - [ ] strlen
